#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
LLM Spider - Function Schemas and Execution

This module provides function schemas and execution for LLM function calling.
"""

import json
import logging
from typing import Dict, Any, List

# Set up logging
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)  # Set to INFO level to capture more logs

# Configure console handler if not already configured
if not logger.handlers:
    console_handler = logging.StreamHandler()
    console_handler.setLevel(logging.INFO)
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    console_handler.setFormatter(formatter)
    logger.addHandler(console_handler)

# Define function schemas for LLM function calling
FUNCTION_SCHEMAS = [
    {
        "type": "function",
        "function": {
            "name": "fetch_webpage",
            "description": "Fetch the HTML content of a webpage",
            "parameters": {
                "type": "object",
                "properties": {
                    "url": {
                        "type": "string",
                        "description": "The URL of the webpage to fetch"
                    }
                },
                "required": ["url"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "parse_with_parser",
            "description": "Parse a webpage using LLM-generated parser",
            "parameters": {
                "type": "object",
                "properties": {
                    "url": {
                        "type": "string",
                        "description": "The URL to parse"
                    },
                    "parser_config": {
                        "type": "object",
                        "description": "The parser configuration generated by the LLM"
                    }
                },
                "required": ["url", "parser_config"]
            }
        }
    }
]


class FunctionExecutor:
    """Executes functions called by the LLM."""
    
    def __init__(self, parser_designer=None):
        """Initialize with a reference to the parser designer window."""
        self.parser_designer = parser_designer
        logger.info("FunctionExecutor initialized")
    
    def execute_function(self, function_name: str, args: Dict[str, Any]) -> Dict[str, Any]:
        """Execute a function called by the LLM."""
        logger.info(f"Executing function: {function_name} with args: {json.dumps(args)}")
        
        try:
            if not self.parser_designer:
                error_msg = "Parser designer not initialized"
                logger.error(error_msg)
                return {"error": error_msg}
                
            result = None
            if function_name == "fetch_webpage":
                logger.info(f"Fetching webpage: {args.get('url', '')}")
                result = self.parser_designer._fetch_webpage(args.get("url", ""))
            elif function_name == "parse_with_parser":
                logger.info(f"Parsing with parser: url={args.get('url', '')}")
                result = self.parser_designer._parse_with_parser(
                    args.get("url", ""),
                    args.get("parser_config", {})
                )
            else:
                error_msg = f"Unknown function: {function_name}"
                logger.error(error_msg)
                return {"error": error_msg}
            
            # Log the result (truncate if too large)
            result_str = json.dumps(result)
            if len(result_str) > 500:
                logger.info(f"Function result (truncated): {result_str[:500]}...")
            else:
                logger.info(f"Function result: {result_str}")
                
            return result
        except Exception as e:
            error_msg = f"Error executing function {function_name}: {str(e)}"
            logger.error(error_msg)
            return {"error": str(e)} 